name: Daily regression tests

on:
  schedule:
    - cron: '0 4,15 * * *'
  workflow_dispatch:

jobs:
  tfhubmodels:
    name: "Regression test TF hub models"
    runs-on: ubuntu-20.04
    # Don't run this in everyone's forks.
    if: github.repository == 'iree-org/iree-samples'
    steps:
      - name: Checking out repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Install Python
        uses: actions/setup-python@48e4ac706204bab735867521ba54b3276c883d00 #3.1.3
        with:
          python-version: '3.9'

      - name: Install Deps
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Installed IREE & TF versions
        shell: bash
        run: |
          pip freeze | egrep 'iree|tensorflow|tf-'

      - name: Run LLVMCPU Backend Tests
        shell: bash
        run: |
          lit -v -D FEATURES=hugetest tflitehub

      - name: Run VMVX Backend Tests
        shell: bash
        run: |
          lit -v -D FEATURES=vmvx tflitehub

      # Alerting disabled until it will be monitored regularly again.
      # - name: Posting to Discord
      #   uses: sarisia/actions-status-discord@c193626e5ce172002b8161e116aa897de7ab5383 # v1.10.2
      #   if: ${{ failure() }}
      #   with:
      #     webhook: ${{ secrets.DISCORD_WEBHOOK }}
      #     description: "iree-samples regressions tests failed"
      #     color: 0x0000ff
      #     username: GitHub Actions
